version: "3"
services:
  laravel:
    build:
      context: ./innoscripta-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./innoscripta-api:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql

  react:
    build:
      context: ./innoscripta-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./innoscripta-react:/app

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=news_aggregator
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3307

volumes:
  db_data:
